### ISSUE TITLE
Use ClusterR c++ functions in another package

### ISSUE THREAD

**Issue by drisso** [mlampros/ClusterR#11]
Hi @mlampros ,

thanks for the great package! We're working on a clustering package for single-cell RNA-seq and we were hoping to re-use and extend your mini-batch k-means implementation. We were wondering if you would be OK with exposing the `utils_rcpp.h` header file to dependent packages, so that we don't need to re-implement your functions.

I think (though I'm definitely not a C++ expert) that you can achieve that by copying the header files into a folder in the installed package, like done here:
https://github.com/LTLA/beachmat/blob/master/src/Makevars#L20
https://github.com/LTLA/beachmat/blob/master/src/Makevars.win#L22

So that in our scripts, we should just be able to add

```
#include "ClusterR/utils_rcpp.h"
```

If I'm totally off and there is a better way to access your C++ functions from a dependent package, I'm happy to hear how to do it!

Best,
Davide

**Comment by mlampros** [comment]
hello @drisso,

I'm not an expert in C++ too, but I hope I can be of help here. As I mentioned in the *References* part of the ClusterR documentation the *mini-batch k-means* implementation is heavily based on a [C code project](https://github.com/siddharth-agrawal/Mini-Batch-K-Means). 
Using Rcpp code from another package is an interesting topic and I've thought about this in the past. I guess there are many similar implementations (besides the one you've already mentioned) and I've found the following : 
* [Rcpp - Linking to DLL from another package?](http://r.789695.n4.nabble.com/Rcpp-Linking-to-DLL-from-another-package-td4747265.html)
* [RcppNumerical](https://github.com/yixuan/RcppNumerical)

Let me see how this can be done and I'll come back with a solution.

**Comment by drisso** [comment]
Thanks! Let me know if I can help!

**Comment by mlampros** [comment]
@drisso I've added the new functionality. I also updated the [README.md](https://github.com/mlampros/ClusterR/blob/master/README.md) file with details on how to call the ClusterR Rcpp code from another package. The updated version was tested on Linux, Macintosh and Windows. Is this what you actually had in mind? I'll be glad if you test it before I submit to CRAN so that I'm able to do any potential adjustments.

**Comment by drisso** [comment]
Awesome! Thank you so much! We will test it as soon as possible (this or next week) and let you know if everything works as expected!

**Comment by drisso** [comment]
Hi @mlampros 

thank you again for adding this functionality so quickly! We can now confirm that we are able to use your C++ functions in our package's C++ code!

**Comment by mlampros** [comment]
@drisso I'd like to know if you intend to use the ClusterR package in a CRAN package. I ask you because for a few days I won't have access to a windows machine to test-check the new version before I submit the new version to CRAN. Therefore the new version might take probably a week to be uploaded on CRAN.

**Comment by drisso** [comment]
Hi @mlampros ,

our package will be on GitHub for now. We plan to submit it to Bioconductor later this year, but not in the too near future, so no hurry for you to update the CRAN version! Thanks for all your work!

**Comment by mlampros** [comment]
@drisso  thanks for the response. I'll close the issue for now feel free to reopen it in case that the new version of the package does not work as expected.

**Comment by mlampros** [comment]
@drisso I know this issue is closed, however I updated the *README.md* file by removing unnecessary calls of *ClusterR* in *depends*, *imports* (*DESCRIPTION* file) and in the *NAMESPACE* file. 
I have to add this comment also as a reference for future users.
