### ISSUE TITLE
How to change the distance in k-means clustering

### ISSUE THREAD

**Issue by yaqiangzheng** [mlampros/ClusterR#13]
Hello
    I am a beginner for R. I want to do kmeans clustering in ClusterR packages， I want try other distance. but  I can not find arguments about distance. How to change the distance in n ClusterR packages?  I'm happy to hear how to do it!
Best,
Zheng yaqiang

**Comment by mlampros** [comment]
@yaqiangzheng I'm sorry for the late reply,

the kmeans algorithm uses by default a single distance to cluster data points. In my implementation I use the WSSE (Within Sum of Squared Error) for this purpose. You might find this [question](https://discuss.analyticsvidhya.com/t/what-is-within-cluster-sum-of-squares-by-cluster-in-k-means/2706/2) that I found on the web informative.
In case that you want to use another distance function, then the [Cluster_medoids](https://rdrr.io/cran/ClusterR/man/Cluster_Medoids.html) (small to medium datasets) and [Clara_medoids](https://rdrr.io/cran/ClusterR/man/Clara_Medoids.html) (for big data sets) allow you to use various distance metrics.

**Comment by yaqiangzheng** [comment]
Thanks for the in depth reply.   I will try and follow the tutorial in the link.
