### ISSUE TITLE
How do you show each cluster as a separate image ?

### ISSUE THREAD

**Issue by smone00** [mlampros/ClusterR#14]
Hi Lampros,

Thanks for the ClusterR packet.
I used this packet to apply kmeans based **grayscale** image clustering with the following codes;

clusteredIm = KMeans_rcpp(im, clusters = 3, num_init = 3, max_iters = 100, 
                      initializer = 'kmeans++', verbose = F)

getcenters = clusteredIm$centroids
getclusters = clusteredIm$clusters
new_im = getcenters[getclusters, ]

I must show each cluster as a new image having the same size with the input image (which is 2 dimensional, e.g., 512x512, 1024x1024, etc)
Is this possible? How?

**Comment by mlampros** [comment]
@smone00,

for grayscale images have a look to the next code chunk which is modified for 2-dimensional data,

```R

library(OpenImageR)

path = 'elephant.jpg'

im = readImage(path)

dim(im)


# convert to grayscale

im = OpenImageR::rgb_2gray(im) 


# first resize the image to reduce the dimensions

im = resizeImage(im, 75, 75, method = 'bilinear')            

imageShow(im)                                                # plot the original image


# create a 1-column-matrix to perform vector-quantization

im2 = matrix(as.vector(im), nrow = nrow(im) * ncol(im), ncol = 1)

dim(im2)


# perform KMeans_rcpp clustering  [ a high 'clusters' parameter might give an error for a 1-column-matrix ]

km_rc = ClusterR::KMeans_rcpp(im2, clusters = 3, num_init = 5, max_iters = 100, 
                              initializer = 'optimal_init', verbose = F)

# km_rc$between.SS_DIV_total.SS

getcent = km_rc$centroids

getclust = km_rc$clusters

new_im = getcent[getclust, ]     # each observation is associated with the nearby centroid

new_im = matrix(new_im, nrow = nrow(im), ncol = ncol(im))

dim(new_im)

imageShow(new_im)

```

However be aware that due to the fact that I use a single-column-matrix as input to the "ClusterR::KMeans_rcpp()" function a high "clusters" parameter value might give an error. In that case you might consider converting your gray scale images to 3-dim as I did in the [code snippet of the 'SuperpixelImageSegmentation' package issue](https://github.com/mlampros/SuperpixelImageSegmentation/issues/1#issuecomment-457162024) using *conv_to_3d = OpenImageR::List_2_Array(list(gray_scale, gray_scale, gray_scale)* and then continue in the same way as in the [example from the blog-post (section "KMeans_rcpp" )](http://mlampros.github.io/2016/09/12/clusterR_package/)

**Comment by smone00** [comment]
Thank you mlampros,

I have already converted it into grayscale by looking at your codes (at https://github.com/mlampros/SuperpixelImageSegmentation/issues/1#issuecomment-457162024)
Thanks again for it.

And then, I have already written the codes from your blog-post (section KMeans_rcpp)

To see one cluster as an image, lets say for the 1st cluster, I have added the following codes;
1stCluster = im3d[km_rc$clusters==1, ]  
imageShow(1stCluster)

However, neither an error nor the expected image is shown :(
The plot window is empty, I could not show the image 1stCluster.

The whole codes are given below. Could you please look at these codes and help me, what is the problem

conv_to_3d = OpenImageR::List_2_Array(list(imGryscale, imGryscale, imGryscale))
dim(conv_to_3d)
OpenImageR::imageShow(conv_to_3d)
im3d = apply(conv_to_3d, 3, as.vector)                                # vectorize 

dim(im3d) 
start = Sys.time()
km_init = KMeans_rcpp(im3d, clusters = 3, num_init = 3, max_iters = 100, 
                                            initializer = 'kmeans++', verbose = F)

end = Sys.time()
t = end - start
cat('time to complete :', t, attributes(t)$units, '\n')

getcent_init = km_init$centroids
getclust_init = km_init$clusters

new_im_init = getcent_init[getclust_init, ]  # each observation is associated with the nearby centroid
dim(new_im_init) = c(nrow(imGryscale), ncol(imGryscale), 3)     # back-convertion to a 3-dimensional 

cluster1 = im3d[km_init$clusters == 1, ]
OpenImageR::imageShow(cluster1)

**Comment by mlampros** [comment]
If I understand you correctly then you want to plot each cluster separately,

```R

........

km_rc = ClusterR::KMeans_rcpp(im2, clusters = 3, num_init = 5, max_iters = 100, 
                              initializer = 'optimal_init', verbose = F)

getcent = km_rc$centroids

getclust = km_rc$clusters

masks_lst = list()

for (j in sort(unique(getclust))) {

  mt = matrix(0, nrow = nrow(im2), ncol = ncol(im2))
  
  for (i in 1:length(getclust)) {
    
    if (getclust[i] == j) {
      
      mt[i, ] = as.vector(getcent[, j])
    }
  }
  
  masks_lst[[j]] = mt
}


lapply(masks_lst, dim)

out = list()

for (i in 1:length(masks_lst)) {
  
  tmp = masks_lst[[i]]
  
  dim(tmp) = c(nrow(im), ncol(im), 3)
  
  out[[i]] = tmp
}

lapply(out, dim)

for (k in 1:length(out)) {
  OpenImageR::imageShow(out[[k]])
  Sys.sleep(4)
}


validate = lapply(masks_lst, function(x) length(which(rowSums(x) > 0)))

table(getclust)

```

let me know if it gave the expected result.

**Comment by smone00** [comment]
Yes, I want to show each cluster separately as saparate images (each of these images should have the same size with the input image)

Thanks. I run the above codes, but got the following error:
> for (k in 1:length(out)) {
+     OpenImageR::imageShow(out[[k]])
+     Sys.sleep(4)
+ }
Error in out[[k]] : subscript out of bounds
In addition: Warning message:
In OpenImageR::imageShow(out[[k]]) :
  restarting interrupted promise evaluation

Whole codes are below:
imGryscale = OpenImageR::readImage(path_km)

OpenImageR::imageShow(imGryscale)

conv_to_3d = OpenImageR::List_2_Array(list(imGryscale, imGryscale, imGryscale))
dim(conv_to_3d)
OpenImageR::imageShow(conv_to_3d)

im3d = apply(conv_to_3d, 3, as.vector)                                # vectorize 

dim(im3d) 

start = Sys.time()

km_init = KMeans_rcpp(im3d, clusters = 3, num_init = 3, max_iters = 100, 
                                    initializer = 'kmeans++', verbose = F)

end = Sys.time()
t = end - start
cat('time to complete :', t, attributes(t)$units, '\n')

getcent = km_init$centroids
getclust = km_init$clusters

masks_lst = list()

for (j in sort(unique(getclust))) {
  
  mt = matrix(0, nrow = nrow(im3d), ncol = ncol(im3d))
  
  for (i in 1:length(getclust)) {
    
    if (getclust[i] == j) {
      
      mt[i, ] = as.vector(getcent[, j])
    }
  }
  
  masks_lst[[j]] = mt
}


lapply(masks_lst, dim)

out = list()

for (i in 1:length(masks_lst)) {
  
  tmp = masks_lst[[i]]
  
  dim(tmp) = c(nrow(im3d), ncol(im3d), 3)
  
  out[[i]] = tmp
}

lapply(out, dim)

for (k in 1:length(out)) {
  OpenImageR::imageShow(out[[k]])
  Sys.sleep(4)
}
validate = lapply(masks_lst, function(x) length(which(rowSums(x) > 0)))
table(getclust)

**Comment by smone00** [comment]
I have forgotten to write the first error, which is;

> out = list()
> 
> for (i in 1:length(masks_lst)) {
+     tmp = masks_lst[[i]]
+     dim(tmp) = c(nrow(im3d), ncol(im3d), 3)
+     out[[i]] = tmp
+ }
Error in dim(tmp) <- c(nrow(im3d), ncol(im3d), 3) : 
  dims [product 37748736] do not match the length of object [12582912]

**Comment by mlampros** [comment]
@smone00,
would you mind [downloading the 'elephant' image](https://github.com/mlampros/mlampros.github.io/blob/master/images/elephant.jpg) and run the following code (then use / adjust the code snippet for your image). It shouldn't give an error,

```R

library(OpenImageR)

path = 'elephant.jpg'

im = readImage(path)

dim(im)

# convert to grayscale

im = OpenImageR::rgb_2gray(im)

# first resize the image to reduce the dimensions
imGryscale = resizeImage(im, 75, 75, method = 'bilinear')            

imageShow(imGryscale)                                                # plot the original image

# im2 = matrix(as.vector(im), nrow = nrow(im) * ncol(im), ncol = 1)

conv_to_3d = OpenImageR::List_2_Array(list(imGryscale, imGryscale, imGryscale))

im2 = apply(conv_to_3d, 3, as.vector) # vectorize

dim(im2)

# perform KMeans_rcpp clustering

km_rc = ClusterR::KMeans_rcpp(im2, clusters = 3, num_init = 5, max_iters = 100, 
                              initializer = 'optimal_init', verbose = F)

# km_rc$between.SS_DIV_total.SS

getcent = km_rc$centroids

getclust = km_rc$clusters

masks_lst = list()

for (j in sort(unique(getclust))) {

  mt = matrix(0, nrow = nrow(im2), ncol = ncol(im2))
  
  for (i in 1:length(getclust)) {
    
    if (getclust[i] == j) {
      
      mt[i, ] = as.vector(getcent[, j])
    }
  }
  
  masks_lst[[j]] = mt
}


lapply(masks_lst, dim)

out = list()

for (i in 1:length(masks_lst)) {
  
  tmp = masks_lst[[i]]
  
  dim(tmp) = c(nrow(conv_to_3d), ncol(conv_to_3d), 3)
  
  out[[i]] = tmp
}

lapply(out, dim)

for (k in 1:length(out)) {
  OpenImageR::imageShow(out[[k]])
  Sys.sleep(4)
}


validate = lapply(masks_lst, function(x) length(which(rowSums(x) > 0)))

all(unlist(validate), table(getclust))

```

**Comment by smone00** [comment]
Thanks, the above codes gives clusters separately as we need.

I have tried to edit these codes again to find solution but I am sorry :(
The problem is that our grayscale images might have different graylevels. So, sometimes we need to cluster our images into 3 clusters, sometimes we need to cluster them into 4 or 5 clusters.

I am getting the following error when I want to cluster the image into 4 clusters;

> for (j in sort(unique(getclust))) {
+     mt = matrix(0, nrow = nrow(im2), ncol = ncol(im2))
+     for (i in 1:length(getclust)) {
+         if (getclust[i] == j) {
+             mt[i, ] = as.vector(getcent[, j])
+         }
+     }
+     masks_lst[[j]] = mt
+ }
Error in mt[i, ] <- as.vector(getcent[, j]) : 
  number of items to replace is not a multiple of replacement length

The other problem is that we need to show 3th and 4th clusters at the same image if we cluster an image into 4 clusters. How can we do this?

**Comment by mlampros** [comment]
@smone00,

just for your information. When an R user opens an issue to a package repository then the issue is related with the package itself. I don't see any relatedness of your issue with the ClusterR package. If you want to ask general questions about clustering or R programming then probably you have to visit specific forums or to participate in R programming courses. I did the same thing.
