### ISSUE TITLE
Package ‘ClusterR’ Manual Needs Attention

### ISSUE THREAD

**Issue by mccurcio** [mlampros/ClusterR#16]
On page 14 of the Package ‘ClusterR’ manual there is a portion of the manual that is not readable. I am seeking clarification on this issue.

Under the KMeans_arma section, 
under the Arguments subsection, 
The item: seed_mode  
- how the initial centroids are seeded. One of,keep_existing,static_subset,random_subset,static_spread,ran

The definition for the seed_mode runs off the page of the pdf and cannot be read.
![clusterR-package-manual-2019-07-07 21-39-13](https://user-images.githubusercontent.com/1915749/60777327-d90b1e80-a0ff-11e9-875c-c0ac6e9f0d44.png)

**Comment by mlampros** [comment]
@mccurcio thanks for making me aware of this. 
The *seed_mode* parameter appears in more than one functions of the *ClusterR* package (GMM, Optimal_Clusters_GMM ) but this issue occurs only in the *KMeans_arma* function of the .pdf manual. 
I added empty spaces between the seed-modes and not it works as expected,

![clusterr_seed_mode](https://user-images.githubusercontent.com/3055514/60787954-1a351a00-a164-11e9-9b9f-c2d4a136be61.png)

I've uploaded the updated version to Github and updated the [NEWS.md](https://github.com/mlampros/ClusterR/blob/master/NEWS.md) file. The changes will be visible in the next CRAN version of the package.
