### ISSUE TITLE
Cannot Install ClusterR on Windows

### ISSUE THREAD

**Issue by maronro** [mlampros/ClusterR#18]
Hi - I am running into a similar issue as others but I can't seem to find a solution for windows OS. I was able to install OpenImageR however the gmp package seems to be the one causing an issue.  Below is the error I receive. Any ideas??

* installing *source* package 'gmp' ...
** package 'gmp' successfully unpacked and MD5 sums checked

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************

** libs

*** arch - i386
C:/RBuildTools/3.4/mingw_32/bin/g++  -std=c++0x -I"C:/PROGRA~1/R/R-33~1.0/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c apply.cc -o apply.o
In file included from biginteger.h:18:0,
                 from bigmod.h:16,
                 from bigvec.h:17,
                 from bigintegerR.h:16,
                 from apply.cc:8:
Rgmp.h:9:17: fatal error: gmp.h: No such file or directory
 #include <gmp.h>
                 ^
compilation terminated.
make: *** [apply.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.0/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.0/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="gmp.dll" OBJECTS="apply.o biginteger.o bigintegerR.o bigmod.o bigrational.o bigrationalR.o bigvec.o bigvec_q.o extract_matrix.o factor.o factorize.o init.o matrix.o matrixq.o solve.o"' had status 2
ERROR: compilation failed for package 'gmp'
* removing 'C:/Users/maronro/Documents/R/win-library/3.3/gmp'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.0/bin/x64/R" CMD INSTALL -l "C:\Users\maronro\Documents\R\win-library\3.3" C:\Users\maronro\AppData\Local\Temp\RtmpI3eMLG/downloaded_packages/gmp_0.5-13.5.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘gmp’ had non-zero exit status

**Comment by mlampros** [comment]
Hi @maronro,

based on the [CRAN Package Check Results of the gmp Package](https://cran.r-project.org/web/checks/check_results_gmp.html) it can be installed on windows. In the DESCRIPTION file of the package it is mentioned,

```bash

SystemRequirements: gmp (>= 4.2.3)

``` 
As this is a gmp related issue, you probably have to open an issue in the 'gmp' repository or search for an answer on the web. If I remember correctly last time I installed the ClusterR package on windows I didn't face any difficulties. As I see you already have 'RBuildTools' installed.

**Comment by maronro** [comment]
Thanks! I was able to fix the problem by installing it to my 3.5 R Version. I was previously using 3.3 for a specific package.
