### ISSUE TITLE
resetting seed at every call of GMM? 

### ISSUE THREAD

**Issue by ericsc7** [mlampros/ClusterR#21]
Dear mlampros, 
I am currently greatly benefiting from ClusterR via the Spectrum package! However, during an analysis I think I might have stumbled on an undesirable property. 
When running
```
library(Spectrum)
for(zi in 1:5){
  print(zi)
  print(rnorm(10,0,1))
  sc <- Spectrum(circles, maxk = 5)
}
```
After the second run, I keep getting as output for zi
``
[1] -0.8356286  1.5952808  0.3295078 -0.8204684  0.4874291  0.7383247  0.5757814 -0.3053884  1.5117812  0.3898432 
``
I am wondering whether this may be due to how the GMM function (which is called in Spectrum) is defined: 

`
GMM = function(data, gaussian_comps = 1, dist_mode = 'eucl_dist', seed_mode = 'random_subset', km_iter = 10, em_iter = 5, verbose = FALSE, var_floor = 1e-10, seed = 1)
`
Thus each run of Spectrum, or GMM, seems to reset the seed, which might lead to some unintended behaviour. 

Thank you very much. 
Best,
Eric

**Comment by mlampros** [comment]
Hi @ericsc7 and I'm sorry for the late reply,

I took a look to the [code of the Spectrum package](https://github.com/cran/Spectrum) package and the **ClusterR::GMM()** function is called in 3 places ([here](https://github.com/cran/Spectrum/blob/master/R/core_functions.R#L144), [here](https://github.com/cran/Spectrum/blob/master/R/spectrum.R#L239) and [here](https://github.com/cran/Spectrum/blob/master/R/spectrum.R#L287)).
It seems that in all 3 cases the [default seed of 1](https://github.com/mlampros/ClusterR/blob/master/R/clustering_functions.R#L61) is used, therefore I would expect (at least) what the **ClusterR::GMM()** code concerns that you would receive the same output if the function is run repeatedly.
