### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by KhatriVivek** [mlampros/ClusterR#26]
Please briefly describe your problem and what output you expect. If you have a question, you also have the option of 
![image](https://user-images.githubusercontent.com/7810426/157980245-cbb4c150-c192-4f88-a0d8-2794172ccb79.png)

Please give a brief description of the problem

configure: error: Header file gmp.h not found; maybe use --with-gmp-include=INCLUDE_PATH
ERROR: configuration failed for package ‘gmp’
* removing ‘/home/jupyter/.R/library/gmp’
ERROR: dependency ‘gmp’ is not available for package ‘ClusterR’
* removing ‘/home/jupyter/.R/library/ClusterR’

The downloaded source packages are in
        ‘/tmp/Rtmpd0gtrP/downloaded_packages’
Warning messages:
1: In install.packages("ClusterR") :
  installation of package ‘gmp’ had non-zero exit status
2: In install.packages("ClusterR") :
  installation of package ‘ClusterR’ had non-zero exit status

Please add your Operating System (e.g., Windows10, Macintosh, Linux) and the R version that you use (e.g., 3.6.2)

Linux

If my package uses Python (via 'reticulate') then please add also the Python version (e.g., Python 3.8) and the 'reticulate' version (e.g., 1.18.0)

**Comment by KhatriVivek** [comment]
Linux in the Google Cloud Platform environment

**Comment by KhatriVivek** [comment]
R 4.1.1

**Comment by mlampros** [comment]
hi @KhatriVivek,
it seems that libgmp is not install in your Linux instance. First, you have to install this system requirement using,

```
sudo apt-get install libgmp3-dev
```
and then retry installing the ClusterR package.

**Comment by KhatriVivek** [comment]
Thank you so much. Now the package installs successfully. Have a great day
