### ISSUE TITLE
the references of  "Optimal_Clusters_KMeans" https://core.ac.uk/download/pdf/205410925.pdf, cannot open

### ISSUE THREAD

**Issue by A-Pai** [mlampros/ClusterR#27]
the references of  "Optimal_Clusters_KMeans"
https://core.ac.uk/download/pdf/205410925.pdf, cannot open，what is the name of the paper？can we get it by google？
![image](https://user-images.githubusercontent.com/5112397/187585009-ec8b9846-7d89-4cfb-aab0-793611b61575.png)

**Comment by mlampros** [comment]
@A-Pai it seems this weblink is the same as 
https://www.ee.columbia.edu/~dpwe/papers/PhamDN05-kmeans.pdf
I'll adjust the documentation and upload the updated one in the Github repo. Thanks for making me aware

**Comment by mlampros** [comment]
I uploaded the updated version, you can use `remotes::install_github('mlampros/ClusterR'` to install the updated version.

**Comment by mlampros** [comment]
I'll close the issue for now. Feel free to re-open it in case that the web link does not work as expected.
