### ISSUE TITLE
Are the effect of “variance_explained”  and “WCSSE”  the same？

### ISSUE THREAD

**Issue by A-Pai** [mlampros/ClusterR#28]
In the  the function “Optimal_Clusters_KMeans”：
![image](https://user-images.githubusercontent.com/5112397/187586308-a6b00709-b876-4582-b3c3-84432e8a09aa.png)
Are the effect of “variance_explained”  and “WCSSE”  the same？because the “total sum of squares” Is constant

**Comment by mlampros** [comment]
@A-Pai the R code snippets for the [variance_explained](https://github.com/mlampros/ClusterR/blob/master/R/clustering_functions.R#L760-L763) and the [WCSSE](https://github.com/mlampros/ClusterR/blob/master/R/clustering_functions.R#L765-L768) include more information and show the differences between the two metrics regarding the optimal clusters

**Comment by A-Pai** [comment]
> @A-Pai the R code snippets for the [variance_explained](https://github.com/mlampros/ClusterR/blob/master/R/clustering_functions.R#L760-L763) and the [WCSSE](https://github.com/mlampros/ClusterR/blob/master/R/clustering_functions.R#L765-L768) include more information and show the differences between the two metrics regarding the optimal clusters
library(ClusterR)
data(dietary_survey_IBS)
dat <- dietary_survey_IBS[, -ncol(dietary_survey_IBS)]
dat <- center_scale(dat)
par(mfrow = c(2, 1))
v1 <- Optimal_Clusters_KMeans(dat, max_clusters = 10, criterion = "variance_explained", plot_clusters = TRUE)
title('criterion = "variance_explained"')
v2 <- Optimal_Clusters_KMeans(dat, max_clusters = 10, criterion = "WCSSE", plot_clusters = TRUE)
title('criterion = "WCSSE"')
v2 / v1
![image](https://user-images.githubusercontent.com/5112397/187860724-c3a11a9f-fe14-4496-8021-76bf7e8376da.png)
![image](https://user-images.githubusercontent.com/5112397/187860435-65972076-4dfd-40bf-b7d7-dbdae8a3379e.png)
It's just the proportions

**Comment by mlampros** [comment]
why do you divide 'WCSSE' by 'variance_explained'?

[WCSSE](https://github.com/mlampros/ClusterR/blob/master/R/clustering_functions.R#L767) = sum(stats::na.omit(as.vector(km$WCSS_per_cluster)))
[variance_explained](https://github.com/mlampros/ClusterR/blob/master/R/clustering_functions.R#L762) = WCSSE / total_SSE

**Comment by A-Pai** [comment]
What I'm trying to say is that the effect of “WCSSE” and “variance_explained” in this functionis the same, it's just proportional

> why do you divide 'WCSSE' by 'variance_explained'?
> 
> [WCSSE](https://github.com/mlampros/ClusterR/blob/master/R/clustering_functions.R#L767) = sum(stats::na.omit(as.vector(km$WCSS_per_cluster))) [variance_explained](https://github.com/mlampros/ClusterR/blob/master/R/clustering_functions.R#L762) = WCSSE / total_SSE

What I'm trying to say is that the effect of “WCSSE” and “variance_explained” in this functionis the same, it's just proportional

**Comment by mlampros** [comment]
@A-Pai I understand. However, it's a different metric and a user has to decide which one to use.

**Comment by A-Pai** [comment]
I see，thanks for your reply

**Comment by mlampros** [comment]
I'll close the issue for now. Feel free to re-open it in case that the web link does not work as expected.
