### ISSUE TITLE
What's the principle of initializers “optimal_init” and “quantile_init”?

### ISSUE THREAD

**Issue by A-Pai** [mlampros/ClusterR#29]
What's the principle of initializers “optimal_init” and “quantile_init”? Are there any reference？It is hard to understand. What is the meaning of “experimental”？
![image](https://user-images.githubusercontent.com/5112397/188091807-9febe188-28a7-45d5-be44-5555d40ef1bf.png)

**Comment by mlampros** [comment]
During the implementation of the 'ClusterR' package (back in 2016) besides the existing initialization methods I also experimented with a few other methods to find out if these work similarly. This was the reason that I added 'experimental'.
You have to take a look to the Rcpp code for more information. For instance, the weblink shows the Rcpp of the [quantile_init](https://github.com/mlampros/ClusterR/blob/master/inst/include/ClusterRHeader.h#L465)

**Comment by mlampros** [comment]
I'll close the issue for now. Feel free to re-open it in case that the code does not work as expected.
