### ISSUE TITLE
Failure to install R 3.4.0 on Mac El Capitan

### ISSUE THREAD

**Issue by dncnbrn** [mlampros/ClusterR#3]
I've tried the CRAN version and the GitHub version, and neither work. Initially, it failed because of the `gmp` dependency, but I manually installed and now I get this:

Using GitHub PAT from envvar GITHUB_PAT
Downloading GitHub repo mlampros/ClusterR@master
from URL https://api.github.com/repos/mlampros/ClusterR/zipball/master
Installing ClusterR
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/nk/vwrxh1rj72b2tflmmqnd5kqw0000gq/T/RtmpdAoBrk/devtoolsc571217e1d9f/mlampros-ClusterR-a0fb2e4'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘ClusterR’ ...
** libs
clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I../inst/include/ -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/RcppArmadillo/include" -I/usr/local/include  -fopenmp -fPIC  -Wall -g -O2 -c RcppExports.cpp -o RcppExports.o
clang: error: unsupported option '-fopenmp'
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘ClusterR’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ClusterR’
Installation failed: Command failed (1)

sessionInfo below:

R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.13.0

loaded via a namespace (and not attached):
 [1] httr_1.2.1     compiler_3.4.0 R6_2.2.0       tools_3.4.0    withr_1.0.2   
 [6] curl_2.6       memoise_1.1.0  knitr_1.15.1   git2r_0.18.0   digest_0.6.12

**Comment by mlampros** [comment]
I'm sorry for the late reply, 
yes the installation currently fails for the Macintosh osx due to the [gmp error](https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64/gmp-00install.html). The alternative using my github repository also fails probably because your installation does not support OpenMP 

```R
clang: error: unsupported option '-fopenmp'
```
If you are not in a hurry then I would suggest to wait a couple of days till the issue of the gmp package is fixed.  If the issue won't be fixed then I'll contact the maintainer of the gmp package.

**Comment by dncnbrn** [comment]
Thanks for getting back to me - seems best to wait until they sort it at the gap end.

**Comment by mlampros** [comment]
I'll close the issue for now, as I sent an e-mail to the maintainer of the 'gmp' package a few weeks back (27th May), but I didn't get a response. I'm sorry that I can't do anything for that, hopefully the error will be fixed for this Macintosh OS version in the near future.

**Comment by vitasiku** [comment]
@mlampros was 

> clang: error: unsupported option '-fopenmp'

ever fixed. Am facing the same issue on MacOs High Sierra, R: 3.4.0
