### ISSUE TITLE
what is the meaning of “squared norm of the centroids”？

### ISSUE THREAD

**Issue by A-Pai** [mlampros/ClusterR#30]
what is the meaning of “squared norm of the centroids”？
![image](https://user-images.githubusercontent.com/5112397/188096886-5f6cdcb9-3331-40c4-bd9f-467c6abc2d4e.png)
Is it the average distance that the centroids shifts during iteration?

**Comment by mlampros** [comment]
Issues on a Github repository are meant for problems related to the code. You might have to open a stackoverflow issue (or on similar web platform) for information related to clustering terms.

**Comment by mlampros** [comment]
I'll close the issue for now. Feel free to re-open it in case that the code does not work as expected.
