### ISSUE TITLE
why does "KMeans_arma" lacks some features?

### ISSUE THREAD

**Issue by A-Pai** [mlampros/ClusterR#31]
why does "KMeans_arma" lacks some features? just because it is hard to implement with Armadillo？
![image](https://user-images.githubusercontent.com/5112397/188110861-20929ff1-cd07-4047-90a9-dc625dac731d.png)

**Comment by mlampros** [comment]
You have to consult the documentation of each function ([KMeans_rcpp](https://mlampros.github.io/ClusterR/reference/KMeans_rcpp.html) and [KMeans_arma](https://mlampros.github.io/ClusterR/reference/KMeans_arma.html)) and especially the "Value" section where it's described what each function returns. You'll observe that the "KMeans_rcpp" returns more output objects compared to the "KMeans_arma" function.

**Comment by mlampros** [comment]
I'll close the issue for now. Feel free to re-open it in case that the code does not work as expected.

**Comment by mlampros** [comment]
As an addition to mention that the "Kmeans_rcpp" is my implementation whereas the "Kmeans_arma" is a function developed by the Author of the C++ Armadillo library and called directly using RcppArmadillo in R. For more information regarding the "Armadillo" library and the Kmeans function you can consult the [documentation](http://arma.sourceforge.net/docs.html)

**Comment by A-Pai** [comment]
Do you mean that the features of KMeans_arma has been intentionally reduced in order to increase computing speed?
