### ISSUE TITLE
the seed in function Clara_Medoids does not work

### ISSUE THREAD

**Issue by A-Pai** [mlampros/ClusterR#34]
the seed in function Clara_Medoids does not work：

library(ClusterR)

set.seed(11)
x <- rbind(
  matrix(rnorm(1000, sd = 0.3), ncol = 2),
  matrix(rnorm(1000, mean = 1, sd = 0.3), ncol = 2)
)

(cm <- Clara_Medoids(x, clusters = 2, samples = 10, sample_size = 0.2, seed = 1))
(cm <- Clara_Medoids(x, clusters = 2, samples = 10, sample_size = 0.2, seed = 2))

![image](https://user-images.githubusercontent.com/5112397/190568944-06de8699-9b1a-46d3-81b7-1fd6686b2b73.png)

**Comment by mlampros** [comment]
@A-Pai 
Let me have a look into this. It's probably a similar to the ['Cluster_Medoids' issue](https://github.com/mlampros/ClusterR/issues/33)

**Comment by mlampros** [comment]
@A-Pai 

this is what I receive,

```R
require(ClusterR)

set.seed(1)
x <- rbind(
  matrix(rnorm(1000, sd = 0.3), ncol = 2),
  matrix(rnorm(1000, mean = 1, sd = 0.3), ncol = 2)
)

head(x)
#            [,1]         [,2]
#[1,] -0.18793614  0.023190937
#[2,]  0.05509300 -0.089060593
#[3,] -0.25068858 -0.354972672
#[4,]  0.47858424  0.003387807
#[5,]  0.09885233  0.297480311
#[6,] -0.24614052  0.478190236

cm <- Clara_Medoids(x, clusters = 2, samples = 10, sample_size = 0.2, seed = 1)
cm1 <- Clara_Medoids(x, clusters = 2, samples = 10, sample_size = 0.2, seed = 1)
cm2 <- Clara_Medoids(x, clusters = 2, samples = 10, sample_size = 0.2, seed = 2)

if (!all(names(cm) == names(cm1))) stop("The sublist names differ!")

nams = names(cm)
nams

for (item in nams) {
  cat(glue::glue("{item}: {identical(cm[[item]], cm1[[item]])}"), '\n')
}

# call: TRUE 
# medoids: TRUE 
# medoid_indices: TRUE 
# sample_indices: TRUE 
# best_dissimilarity: TRUE 
# clusters: TRUE 
# silhouette_matrix: TRUE 
# fuzzy_probs: TRUE 
# clustering_stats: TRUE 
# dissimilarity_matrix: TRUE 
# distance_metric: TRUE 

for (item in nams) {
  cat(glue::glue("{item}: {identical(cm[[item]], cm2[[item]])}"), '\n')
}

# call: FALSE 
# medoids: FALSE 
# medoid_indices: FALSE 
# sample_indices: FALSE 
# best_dissimilarity: FALSE 
# clusters: FALSE 
# silhouette_matrix: FALSE 
# fuzzy_probs: TRUE 
# clustering_stats: FALSE 
# dissimilarity_matrix: FALSE 
# distance_metric: TRUE 
```
And this is what I would expect from the code, i.e. the `cm` and `cm2` return different objects because the `Clara_Medoids` function is based on different samples each time.
You can also view the the output of `str(cm)` and `str(cm2)`

**Comment by mlampros** [comment]
there was an issue (bug) in the Clara_Medoids function and it was related to the 'seed' parameter. See my comments in #35

**Comment by A-Pai** [comment]
The outcome is same only when "set.seed(11)",it's just a coincidence
