### ISSUE TITLE
Why are the results different？

### ISSUE THREAD

**Issue by A-Pai** [mlampros/ClusterR#36]
library(philentropy)
library(apcluster)
library(ClusterR)

set.seed(1)
n <- 100
cl1 <- cbind(rnorm(n / 2, 0.3, 0.04), rnorm(n / 2, 0.7, 0.04))
cl2 <- cbind(rnorm(n / 2, 0.7, 0.04), rnorm(n / 2, 0.3, 0.04))
x <- rbind(cl1, cl2)

s <- -distance(x, method = "euclidean")
p <- min(s)
(ap <- AP_affinity_propagation(s, p = p, dampfact = 0.9, maxits = 1000, convits = 100))
(apres <- apcluster(s, p = p, lam = 0.9, maxits = 1000, convits = 100))

![image](https://user-images.githubusercontent.com/5112397/192812056-0b27437c-4c66-409e-be72-0af2743f8e6e.png)
![image](https://user-images.githubusercontent.com/5112397/192812299-0d3f48ee-442e-4733-8555-4b89525de448.png)

**Comment by mlampros** [comment]
@A-Pai 
does the following code answer your question (distance matrix modification, 'p' input value)

```R

require(ClusterR)
require(apcluster)

set.seed(1)
n <- 100
cl1 <- cbind(rnorm(n / 2, 0.3, 0.04), rnorm(n / 2, 0.7, 0.04))
cl2 <- cbind(rnorm(n / 2, 0.7, 0.04), rnorm(n / 2, 0.3, 0.04))
dat <- rbind(cl1, cl2)

smt = 1.0 - distance_matrix(dat, method = 'euclidean', upper = TRUE, diagonal = TRUE)
diag(smt) = 0.0

set.seed(1)
ap = AP_affinity_propagation(smt, p = median(as.vector(smt)), dampfact = 0.9, maxits = 1000, convits = 100)
str(ap)

apres <- apcluster(smt, p = median(as.vector(smt)), lam = 0.9, maxits = 1000, convits = 100, seed = 1)
str(apres)

cat(glue::glue("Netsim-ClusterR: {ap$netsim}   Netsim-apcluster: {apres@netsim}"), '\n')
# Netsim-ClusterR: 94   Netsim-apcluster: 94.6106022679641 
cat(glue::glue("Exemplars-ClusterR: {paste(ap$exemplars, collapse = ', ')}   Exemplars-apcluster: {paste(apres@exemplars, collapse = ', ')}"), '\n')
# Exemplars-ClusterR: 22, 29, 64, 76   Exemplars-apcluster: 23, 30, 65, 77

```

**Comment by A-Pai** [comment]
smt = 1.0 - distance_matrix(dat, method = 'euclidean', upper = TRUE, diagonal = TRUE)
diag(smt) = 0.0
---what is the advantage of the above instead of the below？
smt <- -distance_matrix(dat, method = "euclidean", upper = TRUE, diagonal = TRUE)

**Comment by mlampros** [comment]
with affinity propagation you normally use a dissimilarity matrix

**Comment by A-Pai** [comment]
I can not catch your meaning，I want to figure out why you prefer the above instead of the below

**Comment by mlampros** [comment]
It's not a matter of preference, normally you use as input to clustering algorithms (dissimilarity or distance) objects that can give the best results. I also mentioned in another issue you opened in the past that such questions are more appropriate for Stackoverflow because I don't see any issue in the code of the Affinity Propagation algorithm. You can search also on the web for dissimilarity or normalized dissimilarity in combination with Affinity Propagation. As an addition the following also works in a similar way,

```R
require(ClusterR)
require(apcluster)
require(cluster)

set.seed(1)
n <- 100
cl1 <- cbind(rnorm(n / 2, 0.3, 0.04), rnorm(n / 2, 0.7, 0.04))
cl2 <- cbind(rnorm(n / 2, 0.7, 0.04), rnorm(n / 2, 0.3, 0.04))
dat <- rbind(cl1, cl2)

dism = daisy(x = dat, metric = 'euclidean')
# class(dism)
dis_mt = as.matrix(dism)
# dis_mt[1:10, 1:10]

smt = ClusterR::distance_matrix(dat, method = 'euclidean', upper = TRUE, diagonal = TRUE)
diag(smt) = 0.0
# smt[1:10, 1:10]

set.seed(1)
ap = AP_affinity_propagation(smt, p = median(as.vector(smt)), dampfact = 0.9, maxits = 1000, convits = 100)
str(ap)

apres <- apcluster(dis_mt, p = median(as.vector(dis_mt)), lam = 0.9, maxits = 1000, convits = 100, seed = 1)
str(apres)

cat(glue::glue("Netsim-ClusterR: {ap$netsim}   Netsim-apcluster: {apres@netsim}"), '\n')
# Netsim-ClusterR: 62   Netsim-apcluster: 63.5711484938375
cat(glue::glue("Exemplars-ClusterR: {paste(ap$exemplars, collapse = ', ')}   Exemplars-apcluster: {paste(apres@exemplars, collapse = ', ')}"), '\n')
# Exemplars-ClusterR: 5, 55   Exemplars-apcluster: 6, 56 

```
