### ISSUE TITLE
Does the dampfact value affect the number of clusters?

### ISSUE THREAD

**Issue by A-Pai** [mlampros/ClusterR#37]
library(philentropy)
library(apcluster)
library(ClusterR)

set.seed(1)
n <- 100
cl1 <- cbind(rnorm(n / 2, 0.3, 0.04), rnorm(n / 2, 0.7, 0.04))
cl2 <- cbind(rnorm(n / 2, 0.7, 0.04), rnorm(n / 2, 0.3, 0.04))
x <- rbind(cl1, cl2)

s <- -distance(x, method = "euclidean")
p <- min(s)
(AP_affinity_propagation(s, p = p, dampfact = 0.5, maxits = 1000, convits = 100))
(AP_affinity_propagation(s, p = p, dampfact = 0.9, maxits = 1000, convits = 100))

![image](https://user-images.githubusercontent.com/5112397/192817495-f77b74ce-9cdb-4842-b983-2e7bde5345f1.png)
![image](https://user-images.githubusercontent.com/5112397/192817760-bbdc1275-570b-4a7d-9605-92bf93b2bf54.png)

**Comment by mlampros** [comment]
I think all parameters [affect the number of clusters](https://github.com/mlampros/ClusterR/blob/master/inst/include/affinity_propagation.h#L484-L489)
