### ISSUE TITLE
[FR] Is there a way to control the number of threads with the openMP backend?

### ISSUE THREAD

**Issue by FMKerckhof** [mlampros/ClusterR#44]
From `?ClusterR::GMM` documentation I read that "the k-means and EM algorithms will run faster on multi-core machines when OpenMP is enabled in your compiler (eg. -fopenmp in GCC) ". Hence I made sure I had OpenMP installed and made sure to reinstall `RcppArmadillo`. 

So far so good - when I run, indeed a lot of parallelization is performed for each iteration of EM/KMM, but all free cores are used. Given that I am operating on a multi-tenant server (which is not uncommon) this is rather antisocial behavior. I tried setting `OMP_NUM_THREADS ` (using `Sys.setenv()`), but that didn't appear to have any effect - is there an option to control (limit) the number of threads used by `ClusterR::GMM` and `ClusterR::Optimal_Clusters_GMM` ?

**Comment by mlampros** [comment]
@FMKerckhof in the [Armadillo documentation](https://arma.sourceforge.net/docs.html) I see the following for k-means

```The clustering will run faster on multi-core machines when OpenMP is enabled in your compiler (eg. -fopenmp in GCC and clang) ```

and for GMM

```The optimisation algorithms are multi-threaded and can run much quicker on multi-core machines when OpenMP is enabled in your compiler (eg. -fopenmp in GCC and clang)```

and regarding GMM I don't see any parameter where you can control the number of threads used when the code is parallelized using ``` -fopenmp```

In the [ClusterR::GMM() function](https://github.com/mlampros/ClusterR/blob/master/inst/include/ClusterRHeader.h#L1587)  I don't have any threads parameter which means parallelization happens only internally in the Armadillo code and not in the RcppArmadillo functions

**Comment by FMKerckhof** [comment]
Thank you @mlampros , I will see if I can figure out a way with system/user limits because also according to the R mailing list it is not possible (https://lists.r-forge.r-project.org/pipermail/rcpp-devel/2014-August/007922.html) . There used to be a package openMPcontroller, but it has been moved to archive (https://cran.r-project.org/web/packages/OpenMPController/)  - the [codebase](https://github.com/cran/OpenMPController) looks fairly straightforward and the fails were only on clang-fedora but I have no knowledge on C++ so I don't think I can fix this myself.

**Comment by mlampros** [comment]
You can still install an archived package using

```R
remotes::install_version("OpenMPController",version = "0.2-5")
```
the fact that was removed from CRAN does not mean you have to fix any CRAN issues which actually might not affect your task

**Comment by mlampros** [comment]
I hope you found a solution related to OMP_NUM_THREADS.
I'll close the issue for now, feel free to re-open it in case the code does not work as expected.
