### ISSUE TITLE
The solution of package ClusterR 1.3.0  is not best yet

### ISSUE THREAD

**Issue by A-Pai** [mlampros/ClusterR#47]
`
n <- 100 # data size
set.seed(3)
x <- rbind(
  matrix(rnorm(n, sd = 0.25), ncol = 2),
  matrix(rnorm(n, mean = 1, sd = 0.25), ncol = 2)
)

library(ClusterR)
k <- 2 
cm <- Cluster_Medoids(x, k, distance_metric = "euclidean")

print(packageVersion("ClusterR"))
cat("package ClusterR solutuion")
cat("\n")
cat("medoid_indices:", sort(cm$medoid_indices))
cat("\n")
cat("best_dissimilarity:", cm$best_dissimilarity)

library(cluster)
k <- 2 
pm <- pam(x, k, metric = "euclidean")

cat("\n\n")
cat("package cluster solutuion")
cat("\n")
cat("medoid_indices:", sort(pm$id.med))
cat("\n")
cat("best_dissimilarity:", n * pm$objective[2])
`

![image](https://user-images.githubusercontent.com/5112397/218673945-9ca0200d-e351-4aa2-8cd8-2491f48016f9.png)

**Comment by A-Pai** [comment]
![image](https://user-images.githubusercontent.com/5112397/218674277-36192274-22fb-4a7b-aec6-79a26771021c.png)
![image](https://user-images.githubusercontent.com/5112397/218674385-24f40479-c640-4efc-8125-a6a85ef57f5f.png)

**Comment by mlampros** [comment]
@A-Pai, I'm sorry for the late reply.
I included details regarding the differences in the [previous issue that you opened](https://github.com/mlampros/ClusterR/issues/39#issuecomment-1336370395).
I also tested the current implementation of the ClusterR::Cluster_Medoids() function on many datasets and I also added other existing algorithms (R packages). You can read more in [this blog-post](http://mlampros.github.io/2022/12/04/comparison_partition_around_medoid/) (towards the end there are also _bar-plots_ with the differences that appear between the various algorithms for all the datasets)

I'll close the issue. Feel free to re-open in case the code does not work as expected

**Comment by A-Pai** [comment]
I verified the calculation results in matlab：
R code：
`
n <- 100 
set.seed(3)
x <- rbind(
  matrix(rnorm(n, sd = 0.25), ncol = 2),
  matrix(rnorm(n, mean = 1, sd = 0.25), ncol = 2)
)

write.csv(x, "x2.csv", row.names = FALSE)

library(ClusterR)
packageVersion("ClusterR")

k <- 2 
cm <- Cluster_Medoids(x, k, distance_metric = "euclidean")

cat("package ClusterR solutuion")
cat("\n")
cat("medoid_indices:", sort(cm$medoid_indices))
cat("\n")
cat("best_dissimilarity:", cm$best_dissimilarity)
`
![image](https://user-images.githubusercontent.com/5112397/218885079-8f06ed6d-5d57-4532-9261-00b1a30faffb.png)

matlab code：
`x = readmatrix("x2.csv");
[idx,C,sumd,d,midx,info] = kmedoids(x,2,'Distance','euclidean');
sum(sumd)
display(midx);
![image](https://user-images.githubusercontent.com/5112397/218886098-3f4e6b82-3ce2-4b59-a9c0-893436e5d389.png)
