### ISSUE TITLE
Error on 'predict' function while following steps on CRAN

### ISSUE THREAD

**Issue by wichaidi** [mlampros/ClusterR#50]
Hi,

While I was following example steps on CRAN (https://cran.r-project.org/web/packages/ClusterR/vignettes/the_clusterR_package.html), this step yielded error:

pr = predict(gmm, newdata = dat)

Error in UseMethod("predict"): no applicable method for 'predict' applied to an object of class "Gaussian Mixture Models"
Traceback:

After googling, I found that this works (https://rdrr.io/cran/ClusterR/man/predict_GMM.html)

pr = predict_GMM(dat, gmm$centroids, gmm$covariance_matrices, gmm$weights)

I am wondering if it is just me. Below is my sessionInfo(). Thank you

R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ClusterR_1.2.4 gtools_3.8.1

**Comment by mlampros** [comment]
the current version of ClusterR on CRAN is 1.3.0 and it seems that you use 1.2.4

> other attached packages:
> [1] ClusterR_1.2.4 gtools_3.8.1

The 'predict()' function was included in [ClusterR in version 1.2.6 ](https://github.com/mlampros/ClusterR/blob/master/NEWS.md#clusterr-126)

Is it possible that you update to the latest version and retry?
Besides installing from CRAN you can also use the latest version from Github,

```R

remotes::install_github('mlampros/ClusterR', upgrade = 'always', dependencies = TRUE, repos = 'https://cloud.r-project.org/')
 
```

**Comment by mlampros** [comment]
I'll close the issue for now feel free to re-open it in case the code does not work as expected.

**Comment by wichaidi** [comment]
I downloaded the zip file from github (https://github.com/mlampros/ClusterR/archive/refs/heads/master.zip), not from CRAN. Perhaps you can please update the zip file there as well?
