### ISSUE TITLE
what does the meaning of “tol” parameter in function “KMeans_rcpp”？

### ISSUE THREAD

**Issue by A-Pai** [mlampros/ClusterR#55]
what does the meaning of “tol” parameter in function “KMeans_rcpp”？
It is said in the manual：
![image](https://github.com/user-attachments/assets/81f2aa61-a986-4344-8a65-62c30a51afef)
I think it should be “magnitude of change”

**Comment by mlampros** [comment]
@A-Pai probably the [line where this argument ("tol") exists](https://github.com/mlampros/ClusterR/blob/master/inst/include/ClusterRHeader.h#L768) might be helpful. It is used for the convergence of KMeans_rcpp

**Comment by mlampros** [comment]
I'll close the issue for now feel free to re-open if the code does not work as expected
