### ISSUE TITLE
what kind of "distance" used in the "KMeans_rcpp"?

### ISSUE THREAD

**Issue by A-Pai** [mlampros/ClusterR#56]
what kind of "distance" used in the "KMeans_rcpp"? It doesn't seem to be in the manual，Can this be ignored？

**Comment by mlampros** [comment]
@A-Pai observations will be assigned to clusters based on the [Within Sum off Squared Error (WSSE)](https://github.com/mlampros/ClusterR/blob/master/inst/include/ClusterRHeader.h#L750)

**Comment by A-Pai** [comment]
> @A-Pai observations will be assigned to clusters based on the [Within Sum of Squared Error (WSSE)](https://github.com/mlampros/ClusterR/blob/master/inst/include/ClusterRHeader.h#L750)

squared euclidian distance？why？
