### ISSUE TITLE
Silhouette plot, margins too small

### ISSUE THREAD

**Issue by elbamos** [mlampros/ClusterR#7]
```
kmed_clusters <- analyte_data %>%
  select(-id) %>%
  as.matrix() %>%
  Cluster_Medoids(kmed_chosen, threads=2, swap_phase = MEDOID_SWAP)
par(mar=c(0,0,0,0))
Silhouette_Dissimilarity_Plot(kmed_clusters)
```

Produces:
```
Error in plot.new() : figure margins too large
```

Any advice?

**Comment by mlampros** [comment]
@elbamos  I'm sorry for the late reply, 

if *kmed_chosen* ( the *clusters* parameter) is large then probably the silhouette plot does not fit in the pc screen (even if edges of plot dragged / expanded). There was a related issue a few days back for another function but I think it applies to your issue too ([especially the second part of the answer](https://github.com/mlampros/ClusterR/issues/5#issuecomment-364636907)).
Any recommendations are welcome.

**Comment by mlampros** [comment]
I close the issue for now, feel free to reopen it.
